Write-Output "Running Script 1"
Write-Output "ServiceAccountPassword: $ServiceAccountPassword"
Write-Output "ServiceAccountUserName: $ServiceAccountUserName"
Write-Output "SqlPackagePath: $SqlPackagePath"
Write-Output "Deploy-Report-Action: $Action"
Write-Output "Script-Action: $Action"
Write-Output "Publish-Action: $Action"
