name: Install NuGet CLI and Add to PATH (Linux)

on:
  push:
    branches:
      - main

jobs:
  install-nuget:
    runs-on: ubuntu-latest  # Using Linux runner (Ubuntu)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Mono (needed to run nuget.exe on Linux)
      - name: Install Mono
        run: |
          sudo apt update
          sudo apt install mono-complete -y

      # Download NuGet CLI (nuget.exe)
      - name: Download NuGet CLI (nuget.exe)
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o /usr/local/bin/nuget.exe
          ls -l /usr/local/bin/nuget.exe  # Verify that nuget.exe is downloaded

      # Set up NuGet alias within the same shell session and run nuget help
      - name: Set up NuGet alias and Verify Installation
        run: |
          echo "alias nuget='mono /usr/local/bin/nuget.exe'" >> ~/.bashrc  # Add alias to .bashrc
          source ~/.bashrc  # Ensure alias is loaded in current shell session
          nuget help  # Should show the NuGet help menu using the alias
