name: Install NuGet CLI and Add to PATH (Linux)

on:
  push:
    branches:
      - main

jobs:
  install-nuget:
    runs-on: ubuntu-latest  # Using Linux runner (Ubuntu)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Native NuGet CLI for Linux
      - name: Install NuGet CLI
        run: |
          sudo apt update
          sudo apt install -y nuget

      # Verify NuGet CLI is accessible and installed
      - name: Verify NuGet CLI Installation
        run: |
          nuget help  # This should work without needing Mono
