name: Install NuGet CLI and Add to PATH (Linux)

on:
  push:
    branches:
      - main

jobs:
  install-nuget:
    runs-on: ubuntu-latest  # Using Linux runner (Ubuntu)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Download and Install NuGet CLI (Native Linux Binary)
      - name: Install NuGet CLI Manually
        run: |
          curl -L https://github.com/NuGet/Home/releases/latest/download/nuget -o /usr/local/bin/nuget
          chmod +x /usr/local/bin/nuget  # Make it executable
          echo "export PATH=/usr/local/bin:$PATH" >> ~/.bashrc
          echo "export PATH=/usr/local/bin:$PATH" >> ~/.profile
          source ~/.bashrc  # Apply the changes

      # Verify NuGet CLI is accessible and installed
      - name: Verify NuGet CLI Installation
        run: |
          nuget help  # This should work without needing Mono
