name: Install NuGet CLI and Add to PATH (Linux)

on:
  push:
    branches:
      - main

jobs:
  install-nuget:
    runs-on: ubuntu-latest  # Using Linux runner (Ubuntu)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Mono (needed to run nuget.exe on Linux)
      - name: Install Mono
        run: |
          sudo apt update
          sudo apt install mono-complete -y

      # Download NuGet CLI (nuget.exe)
      - name: Download NuGet CLI (nuget.exe)
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o /usr/local/bin/nuget.exe
          ls -l /usr/local/bin/nuget.exe  # Verify that nuget.exe is downloaded

      # Verify Mono installation and nuget.exe presence
      - name: Verify Mono and NuGet
        run: |
          mono --version  # Check if Mono is installed correctly
          ls -l /usr/local/bin/nuget.exe  # Check if nuget.exe exists at the expected location

      # Create an alias for nuget and add it to the shell profile
      - name: Create alias for nuget in bash
        run: |
          echo "alias nuget='mono /usr/local/bin/nuget.exe'" >> ~/.bashrc  # Add alias to .bashrc
          source ~/.bashrc  # Source to load the alias in current session
          echo "Alias added: nuget -> mono /usr/local/bin/nuget.exe"
          
      # Verify NuGet CLI is accessible and installed using nuget help
      - name: Verify NuGet CLI Installation
        run: |
          source ~/.bashrc  # Ensure alias is loaded in the current shell session
          nuget help  # Should show the NuGet help menu
