name: Install NuGet CLI and Add to PATH (Linux)

on:
  push:
    branches:
      - main

jobs:
  install-nuget:
    runs-on: ubuntu-latest  # Using Linux runner (Ubuntu)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Mono (needed to run nuget.exe on Linux)
      - name: Install Mono
        run: |
          sudo apt update
          sudo apt install mono-complete -y

      # Download NuGet CLI (nuget.exe)
      - name: Download NuGet CLI (nuget.exe)
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o /usr/local/bin/nuget.exe
          sudo chmod +x /usr/local/bin/nuget.exe  # Make nuget.exe executable

      # Create a symbolic link for nuget in /usr/local/bin
      - name: Add NuGet CLI to PATH
        run: |
          sudo ln -sf /usr/local/bin/nuget.exe /usr/local/bin/nuget
          echo "Updated PATH: $PATH"

      # Verify NuGet CLI is accessible and installed using nuget help
      - name: Verify NuGet CLI Installation
        run: |
          nuget help  # Should show the NuGet help menu
