name: Install NuGet CLI and Add to PATH (Linux)

on:
  push:
    branches:
      - main

jobs:
  install-nuget:
    runs-on: ubuntu-latest  # Using Linux runner (Ubuntu)

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Mono (needed to run nuget.exe on Linux) if you're using nuget.exe and Mono
      - name: Install Mono (optional)
        run: |
          sudo apt update
          sudo apt install mono-complete -y

      # Download NuGet CLI (nuget.exe)
      - name: Download NuGet CLI (nuget.exe)
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o /usr/local/bin/nuget.exe

      # Identify the shell and source the appropriate configuration file
      - name: Identify shell and source the config
        run: |
          echo "Identifying the shell used by the runner"
          SHELL_NAME=$(ps -p $$ -o comm=)
          echo "Shell detected: $SHELL_NAME"
          
          # Source the appropriate config file based on the shell
          if [ "$SHELL_NAME" = "bash" ]; then
            source ~/.bashrc
          elif [ "$SHELL_NAME" = "zsh" ]; then
            source ~/.zshrc
          else
            source ~/.profile  # Default for other shells like dash
          fi

      # Set up the alias for nuget using mono (for nuget.exe)
      - name: Set up alias for nuget (using Mono if needed)
        run: |
          echo "alias nuget='mono /usr/local/bin/nuget.exe'" >> ~/.bashrc
          echo "alias nuget='mono /usr/local/bin/nuget.exe'" >> ~/.zshrc
          source ~/.bashrc  # Ensure alias is loaded immediately

      # Verify NuGet CLI is accessible and installed using nuget help
      - name: Verify NuGet CLI Installation
        run: |
          source ~/.bashrc  # Ensure alias is loaded in the current shell session
          nuget help  # Should show the NuGet help menu
